language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - BOWERPHP_TOKEN=00fe3b72344a637f8d28696f8a73ef67c9fa64e2

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - phpunit
